-- Pythonic core schema for auth-backed progression, rewards, and leaderboards.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  username text unique not null default ('learner_' || substring(gen_random_uuid()::text, 1, 8)),
  avatar text,
  created_at timestamptz not null default now()
);

create table if not exists public.user_progress (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lesson_id text not null,
  track_id text not null,
  completed_at timestamptz not null default now(),
  unique (user_id, lesson_id)
);

create table if not exists public.daily_activity (
  user_id uuid not null references auth.users(id) on delete cascade,
  activity_date date not null,
  did_complete boolean not null default true,
  created_at timestamptz not null default now(),
  primary key (user_id, activity_date)
);

create table if not exists public.streaks (
  user_id uuid primary key references auth.users(id) on delete cascade,
  current_streak integer not null default 0,
  last_completed_at timestamptz,
  freeze_count integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.xp_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  type text not null,
  amount integer not null,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.coin_wallet (
  user_id uuid primary key references auth.users(id) on delete cascade,
  balance integer not null default 0,
  updated_at timestamptz not null default now()
);

create table if not exists public.coin_events (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  amount integer not null,
  reason text not null,
  meta jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create table if not exists public.hint_purchases (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lesson_id text not null,
  tier text not null check (tier in ('hint1', 'hint2', 'full')),
  cost integer not null check (cost >= 0),
  created_at timestamptz not null default now()
);

create table if not exists public.attempts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lesson_id text not null,
  code_hash text not null,
  verdict text not null check (verdict in ('PASS', 'FAIL')),
  feedback_json jsonb not null default '{}'::jsonb,
  estimated_tokens integer,
  estimated_cost_usd numeric(10, 6),
  created_at timestamptz not null default now()
);

create table if not exists public.groups (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  join_code text not null unique,
  owner_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

create table if not exists public.group_members (
  group_id uuid not null references public.groups(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  joined_at timestamptz not null default now(),
  primary key (group_id, user_id)
);

create table if not exists public.user_badges (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  badge text not null,
  created_at timestamptz not null default now(),
  unique (user_id, badge)
);

create index if not exists idx_user_progress_user_id on public.user_progress(user_id);
create index if not exists idx_daily_activity_user_id on public.daily_activity(user_id);
create index if not exists idx_xp_events_user_id on public.xp_events(user_id);
create index if not exists idx_coin_events_user_id on public.coin_events(user_id);
create index if not exists idx_hint_purchases_user_id on public.hint_purchases(user_id);
create index if not exists idx_attempts_user_id on public.attempts(user_id);
create index if not exists idx_group_members_user_id on public.group_members(user_id);

alter table public.profiles enable row level security;
alter table public.user_progress enable row level security;
alter table public.daily_activity enable row level security;
alter table public.streaks enable row level security;
alter table public.xp_events enable row level security;
alter table public.coin_wallet enable row level security;
alter table public.coin_events enable row level security;
alter table public.hint_purchases enable row level security;
alter table public.attempts enable row level security;
alter table public.groups enable row level security;
alter table public.group_members enable row level security;
alter table public.user_badges enable row level security;

drop policy if exists "profiles own select" on public.profiles;
create policy "profiles own select" on public.profiles for select using (auth.uid() = user_id);
drop policy if exists "profiles own update" on public.profiles;
create policy "profiles own update" on public.profiles for update using (auth.uid() = user_id);
drop policy if exists "profiles own insert" on public.profiles;
create policy "profiles own insert" on public.profiles for insert with check (auth.uid() = user_id);

drop policy if exists "user_progress own select" on public.user_progress;
create policy "user_progress own select" on public.user_progress for select using (auth.uid() = user_id);
drop policy if exists "user_progress own insert" on public.user_progress;
create policy "user_progress own insert" on public.user_progress for insert with check (auth.uid() = user_id);

drop policy if exists "daily_activity own select" on public.daily_activity;
create policy "daily_activity own select" on public.daily_activity for select using (auth.uid() = user_id);
drop policy if exists "daily_activity own write" on public.daily_activity;
create policy "daily_activity own write" on public.daily_activity for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "streaks own select" on public.streaks;
create policy "streaks own select" on public.streaks for select using (auth.uid() = user_id);
drop policy if exists "streaks own update" on public.streaks;
create policy "streaks own update" on public.streaks for update using (auth.uid() = user_id);
drop policy if exists "streaks own insert" on public.streaks;
create policy "streaks own insert" on public.streaks for insert with check (auth.uid() = user_id);

drop policy if exists "xp_events own select" on public.xp_events;
create policy "xp_events own select" on public.xp_events for select using (auth.uid() = user_id);

drop policy if exists "coin_wallet own select" on public.coin_wallet;
create policy "coin_wallet own select" on public.coin_wallet for select using (auth.uid() = user_id);

drop policy if exists "coin_events own select" on public.coin_events;
create policy "coin_events own select" on public.coin_events for select using (auth.uid() = user_id);

drop policy if exists "hint_purchases own select" on public.hint_purchases;
create policy "hint_purchases own select" on public.hint_purchases for select using (auth.uid() = user_id);
drop policy if exists "hint_purchases own insert" on public.hint_purchases;
create policy "hint_purchases own insert" on public.hint_purchases for insert with check (auth.uid() = user_id);

drop policy if exists "attempts own select" on public.attempts;
create policy "attempts own select" on public.attempts for select using (auth.uid() = user_id);
drop policy if exists "attempts own insert" on public.attempts;
create policy "attempts own insert" on public.attempts for insert with check (auth.uid() = user_id);

drop policy if exists "groups members can select" on public.groups;
create policy "groups members can select" on public.groups
for select using (
  auth.uid() = owner_id
  or exists (
    select 1 from public.group_members gm
    where gm.group_id = groups.id and gm.user_id = auth.uid()
  )
);
drop policy if exists "groups owner insert" on public.groups;
create policy "groups owner insert" on public.groups
for insert with check (auth.uid() = owner_id);

drop policy if exists "group_members select own groups" on public.group_members;
create policy "group_members select own groups" on public.group_members
for select using (
  auth.uid() = user_id
  or exists (
    select 1 from public.groups g
    where g.id = group_members.group_id and g.owner_id = auth.uid()
  )
);
drop policy if exists "group_members own insert" on public.group_members;
create policy "group_members own insert" on public.group_members
for insert with check (auth.uid() = user_id);

drop policy if exists "user_badges own select" on public.user_badges;
create policy "user_badges own select" on public.user_badges for select using (auth.uid() = user_id);
drop policy if exists "user_badges own insert" on public.user_badges;
create policy "user_badges own insert" on public.user_badges for insert with check (auth.uid() = user_id);

create or replace function public.bootstrap_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (user_id, username)
  values (new.id, 'learner_' || substring(new.id::text, 1, 8))
  on conflict (user_id) do nothing;

  insert into public.coin_wallet (user_id, balance)
  values (new.id, 100)
  on conflict (user_id) do nothing;

  insert into public.streaks (user_id, current_streak, freeze_count)
  values (new.id, 0, 0)
  on conflict (user_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.bootstrap_new_user();

create or replace function public.ensure_user_rows(p_user_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.coin_wallet (user_id, balance)
  values (p_user_id, 100)
  on conflict (user_id) do nothing;

  insert into public.streaks (user_id, current_streak, freeze_count)
  values (p_user_id, 0, 0)
  on conflict (user_id) do nothing;

  insert into public.profiles (user_id, username)
  values (p_user_id, 'learner_' || substring(p_user_id::text, 1, 8))
  on conflict (user_id) do nothing;
end;
$$;

create or replace function public.get_user_dashboard()
returns table(
  streak integer,
  coins integer,
  total_xp bigint,
  weekly_xp bigint,
  lessons_completed bigint
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  perform public.ensure_user_rows(v_user_id);

  return query
  with xp as (
    select
      coalesce(sum(amount), 0)::bigint as total_xp,
      coalesce(sum(case when created_at >= now() - interval '7 days' then amount else 0 end), 0)::bigint as weekly_xp
    from public.xp_events
    where user_id = v_user_id
  ),
  progress as (
    select count(*)::bigint as lessons_completed
    from public.user_progress
    where user_id = v_user_id
  )
  select
    s.current_streak,
    cw.balance,
    xp.total_xp,
    xp.weekly_xp,
    progress.lessons_completed
  from public.streaks s
  join public.coin_wallet cw on cw.user_id = s.user_id
  cross join xp
  cross join progress
  where s.user_id = v_user_id;
end;
$$;

create or replace function public.complete_lesson_and_award(
  p_lesson_id text,
  p_track_id text,
  p_completed_at timestamptz default now(),
  p_is_daily_mission boolean default false
)
returns table(
  xp_awarded integer,
  coins_awarded integer,
  streak integer,
  coin_balance integer
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_day date := p_completed_at::date;
  v_last_day date;
  v_streak integer;
  v_freeze integer;
  v_first_completion_today boolean := false;
  v_new_streak integer;
  v_xp integer := 0;
  v_coins integer := 0;
  v_balance integer := 0;
begin
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  perform public.ensure_user_rows(v_user_id);

  insert into public.user_progress (user_id, lesson_id, track_id, completed_at)
  values (v_user_id, p_lesson_id, p_track_id, p_completed_at)
  on conflict (user_id, lesson_id) do nothing;

  begin
    insert into public.daily_activity (user_id, activity_date, did_complete)
    values (v_user_id, v_day, true);
    v_first_completion_today := true;
  exception
    when unique_violation then
      v_first_completion_today := false;
  end;

  select current_streak, last_completed_at::date, freeze_count
  into v_streak, v_last_day, v_freeze
  from public.streaks
  where user_id = v_user_id
  for update;

  if v_last_day is null then
    v_new_streak := 1;
  elsif v_day = v_last_day then
    v_new_streak := v_streak;
  elsif v_day - v_last_day <= 2 then
    v_new_streak := v_streak + 1;
  elsif v_freeze > 0 then
    v_new_streak := v_streak + 1;
    v_freeze := v_freeze - 1;
  else
    v_new_streak := 1;
  end if;

  update public.streaks
  set
    current_streak = v_new_streak,
    last_completed_at = p_completed_at,
    freeze_count = v_freeze,
    updated_at = now()
  where user_id = v_user_id;

  if v_first_completion_today then
    v_xp := v_xp + 25;
    v_coins := v_coins + 10;

    if p_is_daily_mission then
      v_xp := v_xp + 20;
      v_coins := v_coins + 15;
    end if;

    if v_new_streak > 0 and v_new_streak % 7 = 0 then
      v_xp := v_xp + 30;
      v_coins := v_coins + 20;
    end if;
  end if;

  if v_xp > 0 then
    insert into public.xp_events (user_id, type, amount, meta)
    values (
      v_user_id,
      case when p_is_daily_mission then 'daily_mission_completion' else 'lesson_completion' end,
      v_xp,
      jsonb_build_object('lesson_id', p_lesson_id, 'track_id', p_track_id)
    );
  end if;

  if v_coins <> 0 then
    insert into public.coin_events (user_id, amount, reason, meta)
    values (
      v_user_id,
      v_coins,
      case when p_is_daily_mission then 'daily_mission_reward' else 'lesson_reward' end,
      jsonb_build_object('lesson_id', p_lesson_id, 'track_id', p_track_id)
    );

    update public.coin_wallet
    set balance = balance + v_coins, updated_at = now()
    where user_id = v_user_id
    returning balance into v_balance;
  else
    select balance into v_balance from public.coin_wallet where user_id = v_user_id;
  end if;

  return query
  select v_xp, v_coins, v_new_streak, v_balance;
end;
$$;

create or replace function public.purchase_hint_tier(
  p_lesson_id text,
  p_tier text,
  p_cost integer
)
returns table(coin_balance integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_balance integer;
begin
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  if p_tier not in ('hint1', 'hint2', 'full') then
    raise exception 'Invalid hint tier';
  end if;

  perform public.ensure_user_rows(v_user_id);

  select balance into v_balance
  from public.coin_wallet
  where user_id = v_user_id
  for update;

  if v_balance < p_cost then
    raise exception 'Insufficient coins';
  end if;

  update public.coin_wallet
  set balance = balance - p_cost, updated_at = now()
  where user_id = v_user_id
  returning balance into v_balance;

  insert into public.coin_events (user_id, amount, reason, meta)
  values (v_user_id, -p_cost, 'hint_purchase', jsonb_build_object('lesson_id', p_lesson_id, 'tier', p_tier));

  insert into public.hint_purchases (user_id, lesson_id, tier, cost)
  values (v_user_id, p_lesson_id, p_tier, p_cost);

  return query select v_balance;
end;
$$;

create or replace function public.purchase_streak_freeze(p_cost integer)
returns table(coin_balance integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_balance integer;
begin
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  perform public.ensure_user_rows(v_user_id);

  select balance into v_balance
  from public.coin_wallet
  where user_id = v_user_id
  for update;

  if v_balance < p_cost then
    raise exception 'Insufficient coins';
  end if;

  update public.coin_wallet
  set balance = balance - p_cost, updated_at = now()
  where user_id = v_user_id
  returning balance into v_balance;

  update public.streaks
  set freeze_count = freeze_count + 1, updated_at = now()
  where user_id = v_user_id;

  insert into public.coin_events (user_id, amount, reason, meta)
  values (v_user_id, -p_cost, 'streak_freeze_purchase', '{}'::jsonb);

  return query select v_balance;
end;
$$;

create or replace function public.create_group_with_code(p_name text)
returns table(id uuid, name text, join_code text)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_join_code text;
  v_group_id uuid;
begin
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  v_join_code := upper(substring(encode(gen_random_bytes(4), 'hex') from 1 for 8));

  insert into public.groups (name, join_code, owner_id)
  values (p_name, v_join_code, v_user_id)
  returning groups.id into v_group_id;

  insert into public.group_members (group_id, user_id)
  values (v_group_id, v_user_id)
  on conflict do nothing;

  return query
  select v_group_id, p_name, v_join_code;
end;
$$;

create or replace function public.join_group_by_code(p_join_code text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_group_id uuid;
begin
  if v_user_id is null then
    raise exception 'Not authenticated';
  end if;

  select g.id into v_group_id
  from public.groups g
  where g.join_code = upper(trim(p_join_code))
  limit 1;

  if v_group_id is null then
    raise exception 'Invalid group code';
  end if;

  insert into public.group_members (group_id, user_id)
  values (v_group_id, v_user_id)
  on conflict do nothing;
end;
$$;

create or replace function public.get_my_groups()
returns table(id uuid, name text, join_code text)
language sql
security definer
set search_path = public
as $$
  select g.id, g.name, g.join_code
  from public.groups g
  join public.group_members gm on gm.group_id = g.id
  where gm.user_id = auth.uid()
  order by g.created_at desc
$$;

create or replace function public.get_leaderboard_page(
  p_scope text,
  p_track_id text default null,
  p_group_id uuid default null,
  p_page integer default 1,
  p_page_size integer default 20
)
returns table(
  rank bigint,
  user_id uuid,
  username text,
  avatar text,
  streak integer,
  total_xp bigint,
  weekly_xp bigint,
  track_id text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_offset integer := greatest((p_page - 1) * p_page_size, 0);
begin
  if p_scope = 'track' then
    return query
    with agg as (
      select
        p.user_id,
        max(pr.username) as username,
        max(pr.avatar) as avatar,
        coalesce(max(s.current_streak), 0) as streak,
        coalesce(sum(x.amount), 0)::bigint as total_xp,
        coalesce(sum(case when x.created_at >= now() - interval '7 days' then x.amount else 0 end), 0)::bigint as weekly_xp
      from public.user_progress p
      join public.profiles pr on pr.user_id = p.user_id
      left join public.streaks s on s.user_id = p.user_id
      left join public.xp_events x on x.user_id = p.user_id and x.meta->>'track_id' = p_track_id
      where p.track_id = p_track_id
      group by p.user_id
    ),
    ranked as (
      select row_number() over (order by agg.total_xp desc, agg.streak desc, agg.user_id) as rank, * from agg
    )
    select ranked.rank, ranked.user_id, ranked.username, ranked.avatar, ranked.streak, ranked.total_xp, ranked.weekly_xp, p_track_id
    from ranked
    order by ranked.rank
    offset v_offset limit p_page_size;
    return;
  end if;

  if p_scope = 'group' then
    return query
    with agg as (
      select
        gm.user_id,
        max(pr.username) as username,
        max(pr.avatar) as avatar,
        coalesce(max(s.current_streak), 0) as streak,
        coalesce(sum(x.amount), 0)::bigint as total_xp,
        coalesce(sum(case when x.created_at >= now() - interval '7 days' then x.amount else 0 end), 0)::bigint as weekly_xp
      from public.group_members gm
      join public.profiles pr on pr.user_id = gm.user_id
      left join public.streaks s on s.user_id = gm.user_id
      left join public.xp_events x on x.user_id = gm.user_id
      where gm.group_id = p_group_id
      group by gm.user_id
    ),
    ranked as (
      select row_number() over (order by agg.total_xp desc, agg.streak desc, agg.user_id) as rank, * from agg
    )
    select ranked.rank, ranked.user_id, ranked.username, ranked.avatar, ranked.streak, ranked.total_xp, ranked.weekly_xp, null::text
    from ranked
    order by ranked.rank
    offset v_offset limit p_page_size;
    return;
  end if;

  if p_scope = 'weekly' then
    return query
    with agg as (
      select
        p.user_id,
        max(p.username) as username,
        max(p.avatar) as avatar,
        coalesce(max(s.current_streak), 0) as streak,
        coalesce(sum(case when x.created_at >= now() - interval '7 days' then x.amount else 0 end), 0)::bigint as total_xp,
        coalesce(sum(case when x.created_at >= now() - interval '7 days' then x.amount else 0 end), 0)::bigint as weekly_xp
      from public.profiles p
      left join public.streaks s on s.user_id = p.user_id
      left join public.xp_events x on x.user_id = p.user_id
      group by p.user_id
    ),
    ranked as (
      select row_number() over (order by agg.weekly_xp desc, agg.streak desc, agg.user_id) as rank, * from agg
    )
    select ranked.rank, ranked.user_id, ranked.username, ranked.avatar, ranked.streak, ranked.total_xp, ranked.weekly_xp, null::text
    from ranked
    order by ranked.rank
    offset v_offset limit p_page_size;
    return;
  end if;

  return query
  with agg as (
    select
      p.user_id,
      max(p.username) as username,
      max(p.avatar) as avatar,
      coalesce(max(s.current_streak), 0) as streak,
      coalesce(sum(x.amount), 0)::bigint as total_xp,
      coalesce(sum(case when x.created_at >= now() - interval '7 days' then x.amount else 0 end), 0)::bigint as weekly_xp
    from public.profiles p
    left join public.streaks s on s.user_id = p.user_id
    left join public.xp_events x on x.user_id = p.user_id
    group by p.user_id
  ),
  ranked as (
    select row_number() over (order by agg.total_xp desc, agg.streak desc, agg.user_id) as rank, * from agg
  )
  select ranked.rank, ranked.user_id, ranked.username, ranked.avatar, ranked.streak, ranked.total_xp, ranked.weekly_xp, null::text
  from ranked
  order by ranked.rank
  offset v_offset limit p_page_size;
end;
$$;
